language: python

branches:
  only:
    - nrgi
    - staging

env:
  global:
    # Shippable API token used to trigger deploy
    - secure: MEFUkaoXFiR2Y2FjMt5qjEAyZyQlAjeIL1ofgVeg9JxAuNCjIkf6Fu8LSC43zocBHCDynpDPmYljDMsj6BNlMdgzlCs4EiMVVihdUIaRaxR+n3fvRlbipcJZifprYmPnPoiVyWuhcuUO3O1+UpTRpjNgqdReWchJgx32iTvAImVju6MoWxLcWbLhFMYJfU+otCMWoh7C9R8A6VyzVCSqwvTT/b2hWeUAPTS6SaPt9uBe2fP8BbLax0hAJLZLTpeeGlZINI2yjgMGX5wdxevdk/Vij6Y+VhLl2p3P/rlUGsEItI+3D3Vl3t9yIEl/6PlikX319u3O/e2noawpv/s4eg==
build:
  ci:
    # Create the version file
    - ./create_version.sh

    # Pull latest image to be used as cache
    - docker pull nrgi/resourcedata.org:$BRANCH || echo 'Cache not available'

    # Use the `--cache-from` option to use the latest image in the repo as a cache for this build. Available since Docker 1.13
    - docker build -t nrgi/resourcedata.org:$BRANCH.$COMMIT --cache-from nrgi/resourcedata.org:$BRANCH .

    # Create the `latest` tag and force it in case the tag is already there from a previous build
    - docker tag nrgi/resourcedata.org:$BRANCH.$COMMIT nrgi/resourcedata.org:$BRANCH

    - docker push nrgi/resourcedata.org:$BRANCH
    - docker push nrgi/resourcedata.org:$BRANCH.$COMMIT

    # Trigger deploy through building a repo with deploy configuration
    - ./shippable-deploy.sh

integrations:
  hub:
    - integrationName: nrgiDockerHub
      type: docker
  notifications:
    - integrationName: email
      type: email
      recipients:
        - nrgi@vitaminsoftware.com
      branches:
        only:
          - nrgi
          - staging
      on_success: change
      on_failure: always
