#!/bin/sh
set -eu

"$CKAN_HOME"/bin/paster --plugin=ckan db init -c "${CKAN_CONFIG}/ckan.ini"
"$CKAN_HOME"/bin/paster --plugin=ckan datastore set-permissions -c "${CKAN_CONFIG}/ckan.ini" | psql -h datastore -U datastore
echo "CREATE EXTENSION postgis; \
      CREATE EXTENSION postgis_topology; \
      CREATE EXTENSION postgis_sfcgal; \
      CREATE EXTENSION fuzzystrmatch; \
      CREATE EXTENSION postgis_tiger_geocoder;" | psql -h datastore -U datastore

