#!/bin/bash

# this will fail if you didn't kill the db too... how best to fix that...
set +e
set -u

# only build if $INITIAL_BUILD is set
DO_BUILD=${INITIAL_BUILD:-0}
if [[ $DO_BUILD -ne 1 ]] ; then exit ; fi


: ${ADMIN_PASSWORD:=}
: ${ADMIN_EMAIL:=}

"$CKAN_HOME"/bin/paster --plugin=ckan user add admin password="$ADMIN_PASSWORD" email="$ADMIN_EMAIL" --config=/etc/ckan/default/ckan.ini
"$CKAN_HOME"/bin/paster --plugin=ckan sysadmin add admin --config=/etc/ckan/default/ckan.ini
